# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkgmate" do
  name "pkgmate"
  desc "TUI application to manage your dependencies"
  homepage "https://github.com/fuad-daoud/pkgmate"
  version "0.16.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkgmate"

  on_macos do
    url "https://github.com/fuad-daoud/pkgmate/releases/download/v#{version}/pkgmate-darwin-universal.tar.gz"
    sha256 "2bb71e0b1d7383dd65b196d9625119325a7c86aaf6ed3deffd8656e680089095"
  end

  # No zap stanza required
end
