# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkgmate" do
  name "pkgmate"
  desc "TUI application to manage your dependencies"
  homepage "https://github.com/fuad-daoud/pkgmate"
  version "0.11.0-test"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkgmate"

  on_macos do
    url "https://github.com/fuad-daoud/pkgmate/releases/download/v#{version}/pkgmate-brew-darwin-universal.tar.gz"
    sha256 "6e32505bb608158a2907ee7eed7ac29d29dcb0f9736d892551be1fb1ee810339"
  end

  # No zap stanza required
end
