# This file was generated by GoReleaser. DO NOT EDIT.
cask "pkgmate" do
  name "pkgmate"
  desc "TUI application to manage your dependencies"
  homepage "https://github.com/fuad-daoud/pkgmate"
  version "0.15.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pkgmate"

  on_macos do
    url "https://github.com/fuad-daoud/pkgmate/releases/download/v#{version}/pkgmate-darwin-universal.tar.gz"
    sha256 "eb7b0e3568edbd0e8e2eb5902f02be6e79ddff510629c71f5bae4375979e7353"
  end

  # No zap stanza required
end
